### ISSUE TITLE
Under 'Why Use Controlled Forms When We Do Not Have To'

### ISSUE THREAD

**Issue by nicklunn325** [learn-co-curriculum/react-forms#18]
Code doesn't work. I added an import of my parent component to my index.js.  I also tried debugging the code myself but in the end the code will not work as it is.  I did not spend to much time debugging but didnt get it to work.  The first error it throws is 

TypeError: Cannot read property 'firstName' of undefined

**Comment by maxwellbenton** [comment]
Hi @nicklunn325,

Thank you for opening this issue and providing feedback. Unfortunately, I was unable to replicate the issue you experienced. I did notice there were no instructions for updating `src/index.js`, so I've added some in, but I've checked the code snippets and they correctly render as is. I also took a look at the components you had in [your clone of the repo](https://github.com/nicklunn325/react-forms-atlanta-web-82619/tree/master/src) and the components you submitted all successfully render when running `npm start`. 

The error you're receiving suggests that `formData` is becoming undefined somewhere along the way, but I do not see this in the code.

Since the code does seem to work as is, I am going to close this issue. However, if there is anything you feel I've missed or if there is additional information on how to replicate this issue, please feel free to reopen this issue.

Thank you!
